FROM node:16.14.0-alpine3.14 as node
WORKDIR /app

# installs
RUN npm install --global yarn --force
RUN yarn set version berry
RUN npm install typescript@4.5.4 -g
# RUN npm install --global lerna@4.0.0

# copy all
COPY . .

# hoisting
RUN yarn install

# build packages workspace(for PreBuild Module)
#Optionanl(공통개발자가 추가/수정 후 PreBuild를 제대로 수행 했다는 가정하에 불필요.)
# RUN yarn build:packages
# RUN yarn build:components
# build dml
RUN yarn build:dml

# nginx 
FROM nginx:1.13.12-alpine
COPY applications/dml/nginx-develop.d/. /etc/nginx/conf.d
COPY --from=node /app/applications/dml/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]